global:
    settings:
        dinkly_version: 1.28

    apps:
        admin:
            default_app: true
            default_module: home
            base_href: /
            app_name: Dinkly Admin
            app_description: Just a humble little PHP MVC Framework
            copyright: Dinkly
        api:
            app_name: Dinkly API
            base_href: /api
            default_module: api
        user:
            app_name: Dinkly User
            base_href: /user
            default_module: home

    databases:
        admin:
            host: localhost
            user: root
            pass: root
            name: dinkly_admin

        unit_test:
            host: localhost
            user: root
            pass: root
            name: dinkly_unit_test
dev:
    apps:
        admin:
            app_name: Dinkly Admin Dev
prod:
    apps:
        admin:
            app_name: Dinkly Admin